- lib/generators/slim/scaffold/templates/index.html.slim
Use Ruby 1.9 hash notation consistently throughout generators
> Ruby 1.9 hash notation use in generators

- slim-rails.gemspec
There is no reason to have a runtime dependency on `actionmailer` (not each rails app needs it). Also a runtime dependency on `activesupport` is redundant because other Rails gems depend on it.
In future it would be good to have runtime dependencies on `railties` and `actionview` only.
> Make actionmailer only as a development dependency

- lib/slim-rails.rb
`app.assets` is only available after the initializers run.
Use configure block to ensure run `register_engine` after `app.assets` initialized.
> Only access environment directly in configure block

- lib/slim-rails/register_engine.rb
I was trying to use `slim-rails` with `sprockets-4.0.0.beta3`, but I get following error. 
```
ArgumentError: wrong number of arguments (4 for 2..3)
/tmp/build_475685566bf37f049b2a69c336bc3224/y-yagi-todo_minder-5e27b12/vendor/bundle/ruby/2.2.0/gems/sprockets-4.0.0.beta3/lib/sprockets/processing.rb:212:in `register_config_processor'
/tmp/build_475685566bf37f049b2a69c336bc3224/y-yagi-todo_minder-5e27b12/vendor/bundle/ruby/2.2.0/gems/sprockets-4.0.0.beta3/lib/sprockets/processing.rb:54:in `register_preprocessor'
/tmp/build_475685566bf37f049b2a69c336bc3224/y-yagi-todo_minder-5e27b12/vendor/bundle/ruby/2.2.0/gems/slim-rails-3.1.1/lib/slim-rails/register_engine.rb:33:in `block in _register_engine'
``` 
As far as code, it does not seem to pass Array to `register_preprocessor`. …
> make work with sprockets 4

- .travis.yml
- test/lib/slim-rails_assets_test.rb
> Bump Ruby versions for Travis

- lib/generators/slim/scaffold/templates/edit.html.slim
- lib/generators/slim/scaffold/templates/show.html.slim
Based on the work at https://github.com/slim-template/slim-rails/pull/85
> Add leading and trailing spaces around Show/Edit/Back links in templates

- lib/slim-rails/register_engine.rb
- test/lib/slim-rails_assets_test.rb
This is an addition to:
https://github.com/slim-template/slim-rails/pull/136
https://github.com/slim-template/slim-rails/pull/132
For Sprockets 3 and 2 we will use `register_engine` , for Sprockets 4 `register_transformer`. 
if we use transformer with Sprockets 3 then Assets Pipeline produces unmodified, fingerprinted files with `.slim` extension (BAD).
> Use transformer for Sprockets 4+ otherwise fallback to engine

- lib/slim-rails/register_engine.rb
`def self.foo` does not define a private method though it is in a private context.
By using `class << self` and `def foo`, we can define a private method on `Slim::Rails::RegisterEngine` module.
> Make _register_engine and _register_engine3 private

- slim-rails.gemspec
Now, `slim` v4.0.0 is latest.
https://rubygems.org/gems/slim/versions/4.0.0
I want to use `slim` v4.0.0 via `slim-rails`. 
Gemfile
```ruby
gem "slim", "4.0.0"
gem "slim-rails", "3.1.3"
```
```bash
$ bundle update
(snip)
Bundler could not find compatible versions for gem "slim":
In Gemfile:
slim (= 4.0.0)
slim-rails (= 3.1.3) was resolved to 3.1.3, which depends on
slim (~> 3.0)
```
So I relaxed dependency.
> Relax dependency for slim v4.0.0

- .travis.yml
- Appraisals
- gemfiles/rails_5.0.gemfile
- gemfiles/rails_edge.gemfile
Improve Travis CI build
- Fix Travis CI config warnings (build and distro entries)
- Test on Focal Fossa
- Sort Rails versions by descending order (newest first)
- Rename rails_5 gemfile to include .0
- Cache bundled dependencies
- Enable Fast Finish
- Do not test Rails 5.x against Ruby 3.0 stable
- Test Rails 5.0 and 5.1 with Sprockets 3
> Improve Travis CI build

- lib/generators/slim/mailer/templates/view.html.slim
- lib/generators/slim/mailer/templates/view.text.slim
- lib/generators/slim/scaffold/templates/_form.html.slim
- lib/generators/slim/scaffold/templates/edit.html.slim
- lib/generators/slim/scaffold/templates/show.html.slim
- slim-rails.gemspec
- test/lib/generators/slim/controller_generator_test.rb
- test/lib/generators/slim/mailer_generator_test.rb
- test/lib/generators/slim/scaffold_generator_test.rb
- test/lib/generators/slim/testing_helper.rb
Default templates will generate the following errors
```
$ rails g scaffold foo
$ rails g mailer baz
$ rails g controller bar index
$ rails slim_lint
app/views/foos/_form.html.slim:4 [W] RuboCop: Style/StringLiteralsInInterpolation: Prefer single-quoted strings inside interpolations.
app/views/foos/edit.html.slim:8 [W] TrailingBlankLines: Multiple empty lines in the end of file
app/views/foos/show.html.slim:3 [W] EmptyLines: Extra empty line detected
```
~### Could we add slim-lint to this gem to prevent those errors in the future?
I guess we couldn't in an easy way because the templates will generate valid slim files but they are not valid slim files~
> Fix templates to make Slim-Lint happy

- lib/slim-rails/register_engine.rb
- test/lib/slim-rails_assets_test.rb
Currently, precompiling Slim templates fails due to `undefined local variable or method` error when asset helpers (e.g. `stylesheet_link_tag`) are used in them.
This PR fixes that by passing `Sprockets::Context` object to `Slim::Template#render`.
> Enable asset helpers in precompiled templates 

- slim-rails.gemspec
Also: This gem exposes 0 executables. And the test_files directive is no longer in use anywhere.
Example where the diff between versions shows unnecessary files: https://my.diffend.io/gems/slim-rails/3.2.0/3.3.0
(I squashed my commit.)
> gemspec: Include fewer files.

- CHANGELOG.md
- lib/slim-rails.rb
- lib/slim-rails/version.rb
`do ... end` blocks are implicit `begin ... end` blocks since Ruby 2.5.
This code was introduced recently in f6be8fcaa3db6b4f1f6536dc2770644f19923716 in an attempt to set up more modern CI but at the same time it made the gem incompatible with Ruby versions older than 2.5
This PR will `rubocop:disable Style/RedundantBegin` and restore old style code.
> Support old Rubies pre 2.5

- slim-rails.gemspec
This commit changes the dependency to the `slim` gem to allow using its version 5.0, that was [released on the 23rd of January 2022][0]
[0]: https://rubygems.org/gems/slim/versions/5.0.0
> Support Slim 5

- README.md
- Add a History section for notes about the past.
- Update link to indirect's haml repo to the current link of that repo, now using https://.
- Make the guide's link text more descriptive.
- Do not promise Rails 3+ support, but note what the earliest-tested Rails version in the testing matrix is, instead.
> README: Separate out details from main things

- lib/generators/slim/scaffold/templates/_form.html.slim.tt
It fixed ActionView::SyntaxErrorInTemplate when scaffolding with namespace.
It is same format with rails v7.x.
https://github.com/rails/rails/blob/v7.0.6/railties/lib/rails/generators/erb/scaffold/templates/_form.html.erb.tt#L1-L12
fixed #192
> Fix ActionView::SyntaxErrorInTemplate when scaffolding with namespace

- .github/workflows/main.yml
- Appraisals
- gemfiles/rails_6.1.gemfile
- gemfiles/rails_7.0.gemfile
- gemfiles/rails_8.0.gemfile
- slim-rails.gemspec
This Pull Request updates the CI matrix for Rails 8.0 / Ruby 3.4.
It also adds dependencies for gems that became part of `bundled gems` in Ruby 3.4 for Rails 7.0 and earlier to the Appraisals file.
To address CI errors occurring in Ruby 3.0 or higher, this Pull Request includes updates to `development_dependency` from the following Pull Request:
- #198
> Add Rails 8.0 & Ruby 3.4 to CI

- slim-rails.gemspec
This Pull Request has been created because CI raises the error of `rexml/document (LoadError)` with ruby 3.0 or higher.
For CI error details, see the following:
```sh
$ bundle exec rake
...
/opt/hostedtoolcache/Ruby/3.3.6/x64/lib/ruby/3.3.0/bundled_gems.rb:69:in `require': cannot load such file -- rexml/document (LoadError)
from /opt/hostedtoolcache/Ruby/3.3.6/x64/lib/ruby/3.3.0/bundled_gems.rb:69:in `block (2 levels) in replace_require'
from /home/runner/work/slim-rails/slim-rails/vendor/bundle/ruby/3.3.0/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:34:in `require'
from /home/runner/work/slim-rails/slim-rails/vendor/bundle/ruby/3.3.0/gems/slim_lint-0.24.0/lib/slim_lint/reporter/checkstyle_reporter.rb:3:in `<top (required)>'
...
``` …
> CI: Update slim_lint version to fix `rexml/document (LoadError)`

- lib/generators/slim/authentication/authentication_generator.rb
- lib/generators/slim/authentication/templates/passwords/edit.html.slim
- lib/generators/slim/authentication/templates/passwords/new.html.slim
- lib/generators/slim/authentication/templates/sessions/new.html.slim
- test/fixtures/application_controller.rb
- test/lib/generators/slim/authentication_generator_test.rb
- test/lib/generators/slim/testing_helper.rb
- test/test_helper.rb
This Pull Request adds support for the Rails 8.0 authentication generator.
The `Slim::Generators::AuthenticationGenerator` is added to generate the following slim files when running `rails generator authentication`:
- app/views/sessions/new.html.slim
- app/views/passwords/new.html.slim
- app/views/passwords/edit.html.slim
The contents of the generated slim files are equivalent to the ERB files used in the authentication generator templates from the `rails/rails` repository.
- https://github.com/rails/rails/tree/v8.0.1/railties/lib/rails/generators/erb/authentication/templates/app/views
Since the authentication generator is a feature introduced in Rails 8.0, the `AuthenticationGenerator` tests are skipped when running `slim-rails` tests on Rails versions below 8.0.
- …
> Support Rails 8.0 authentication generator
